package models

type Section string

const (
    SectionAllowanceAndLoanMixA               Section = "Allowance and Loan Mix-a"
    SectionAllowanceAndLoanMixB               Section = "Allowance and Loan Mix-b"
    SectionAssetYieldsAndFundingCosts         Section = "Asset Yields and Funding Costs"
    SectionBalanceSheetDollar                 Section = "Balance Sheet dollar"
    SectionBalanceSheetPercent                Section = "Balance Sheet percent"
    SectionCapitalAnalysisA                   Section = "Capital Analysis-a"
    SectionCapitalAnalysisB                   Section = "Capital Analysis-b"
    SectionCapitalAnalysisC                   Section = "Capital Analysis-c"
    SectionCapitalAnalysisD                   Section = "Capital Analysis-d"
    SectionConcentrationsOfCredit             Section = "Concentrations of Credit"
    SectionConceptNotInPresentation           Section = "Concept Not In Presentation"
    SectionDerivativeAnalysis                 Section = "Derivative Analysis"
    SectionDerivativeInstruments              Section = "Derivative Instruments"
    SectionExecutiveSummaryReport             Section = "Executive Summary Report"
    SectionFiduciaryServicesA                 Section = "Fiduciary Services-a"
    SectionFiduciaryServicesB                 Section = "Fiduciary Services-b"
    SectionIncomeStatement1QtrAnn             Section = "Income Statement 1-Qtr-Ann"
    SectionIncomeStatementDollar              Section = "Income Statement dollar"
    SectionInterestRateRisk                   Section = "Interest Rate Risk"
    SectionLiquidityAndFunding               Section = "Liquidity and Funding"
    SectionLiquidityAndInvPortfolio           Section = "Liquidity and Inv Portfolio"
    SectionNoninterestIncomeAndExpenses      Section = "Noninterest Income and Expenses"
    SectionOffBalanceSheetItems               Section = "Off Balance Sheet Items"
    SectionPDNonaccAndRestLoansA              Section = "PD, Nonacc and Rest Loans-a"
    SectionPDNonaccAndRestLoansB              Section = "PD, Nonacc and Rest Loans-b"
    SectionQTRIncomeStatementDollar           Section = "QTR Income Statement dollar"
    SectionSecuritizationAndAssetSaleA        Section = "Securitization and Asset Sale-a"
    SectionSecuritizationAndAssetSaleB        Section = "Securitization and Asset Sale-b"
    SectionSecuritizationAndAssetSaleC        Section = "Securitization and Asset Sale-c"
    SectionSummaryRatios                      Section = "Summary Ratios"
)
